# Generated by Django 3.2.16 on 2022-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('latency', models.FloatField()),
                ('cpu', models.FloatField()),
                ('ram', models.IntegerField()),
            ],
        ),
    ]
